version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: NFe.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - nfe-network

  worker:
    build:
      context: .
      dockerfile: NFe.Worker/Dockerfile
    depends_on:
      - db
      - api
    networks:
      - nfe-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=NFeEmitter@2025
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - nfe-network

networks:
  nfe-network:
    driver: bridge

volumes:
  sqldata:
