version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: NFe.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=nfedb;Username=nfeadmin;Password=NFeSecurePass2025!
    depends_on:
      - db
    networks:
      - nfe-network

  worker:
    build:
      context: .
      dockerfile: NFe.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=nfedb;Username=nfeadmin;Password=NFeSecurePass2025!
    depends_on:
      - db
      - api
    networks:
      - nfe-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=nfedb
      - POSTGRES_USER=nfeadmin
      - POSTGRES_PASSWORD=NFeSecurePass2025!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nfe-network

networks:
  nfe-network:
    driver: bridge

volumes:
  pgdata:
